name: MyFirstBukkitPlugin
version: 0.2
main: com.codisimus.myfirstbukkitplugin.MyFirstBukkitPlugin
author: Codisimus
description: a simple plugin
website: www.codisimus.com
permissions:
  myfirstbukkitplugin.greeting:
    description: Needed to see the "Hello World" message
    default: true